# Generated by Django 4.2 on 2024-01-28 12:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocid", models.CharField(max_length=32, unique=True)),
                (
                    "cert_code",
                    models.CharField(
                        default=api.models.generate_random_cert,
                        max_length=14,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
