# Generated by Django 4.2 on 2024-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certdata",
            name="ocid",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
